coa_videolibrary:
  aws_access_key_id: ~
  aws_secret_access_key: ~
  aws_region: ~
  mediaconvert_endpoint: ~
  mediaconvert_role_arn: ~
  s3_bucket: ~
  keys_route: '/keys'
  hls_key_baseurl: ~
  video_entity: ~
  prefix: ~
  constellation:
    name: ~
    id: ~
    enabled: ~
    token: ~