# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    coa_videolibrary:
        aws_access_key_id: ~
        aws_secret_access_key: ~
        aws_region: ~
        mediaconvert_endpoint: ~
        mediaconvert_role_arn: ~
        s3_bucket: ~
        keys_route: '/keys'
        hls_key_baseurl: ~
        video_entity: ~


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Coa\VideolibraryBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'

    Coa\VideolibraryBundle\Command\CoaVideolibraryTranscodeCommand:
        tags:
            - { name: console.command, command: 'coa:videolibrary:transcode' }

    Coa\VideolibraryBundle\Command\CoaVideolibraryFtpCommand:
        tags:
            - { name: console.command, command: 'coa:videolibrary:ftp' }

    Coa\VideolibraryBundle\Command\CoaVideolibraryStatusCommand:
        tags:
            - { name: console.command, command: 'coa:videolibrary:status' }



    Coa\VideolibraryBundle\Extensions\Twig\FormatBytes:
        tags:
            - { name: twig.extension }

    Coa\VideolibraryBundle\Extensions\Twig\FormatDuration:
        tags:
            - { name: twig.extension }